scsi:ufs: Resolve the compile errors
Integrate GKI android12-5.10-2023-11_r7,
have the compile error:
msm-kernel/drivers/scsi/ufs/vendor/ufsfeature.h:53:2:
error: redefinition of enumerator 'UFSHCD_EH_IN_PROGRESS'

Need to remove the redefinition UFSHCD_EH_IN_PROGRESS

Change-Id: I464d5f151f7d53cc94609c3469de5b6e354f715a
Signed-off-by: Zhiye Li <lizy90@motorola.com>
Reviewed-on: https://gerrit.mot.com/3015255
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Liyun Zhang <zhangl19@motorola.com>
Submit-Approved: Liyun Zhang <zhangl19@motorola.com>