ANDROID: GKI: update symbol list for db845c
Enabling configs for Tegra SoCs required these symbols to be included.
This change fixes the following build issues:

  ERROR: modpost: "devm_tegra_memory_controller_get" [drivers/iommu/arm/arm-smmu/arm_smmu.ko] undefined!
  ERROR: modpost: "tegra_mc_probe_device" [drivers/iommu/arm/arm-smmu/arm_smmu.ko] undefined!

Also update the STG file accordingly:
2 function symbol(s) added
  'struct tegra_mc* devm_tegra_memory_controller_get(struct device*)'
  'int tegra_mc_probe_device(struct tegra_mc*, struct device*)'

Bug: 335325897
Change-Id: Ie357116189e074f1dc0e572553b2264abc910bd3
Signed-off-by: Carlos Llamas <cmllamas@google.com>